# MkDocs Configuration
# --------------------

markdown_extensions:
    - toc:
        permalink: true
nav:
  - 'Home': index.md
  - 'API Reference':
      - 'Card': cards.md
      - 'CardList': card-lists.md
      - 'CardSet': card-sets.md
      - 'CardSetCollection': card-set-collections.md
      - 'Deck': decks.md
      - 'graphics': graphics.md
      - 'meta': meta.md
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            filters: ['!^_[^_]']
            show_signature_annotations: false
            show_source: true
          paths: ['src']
  - search
repo_name: HarrisonTotty/fab
repo_url: https://github.com/HarrisonTotty/fab
site_name: Flesh and Blood TCG Analysis Library
theme:
  name: material
