# MkDocs Configuration
# --------------------

nav:
  - index.md
  - 'Card Objects': cards.md
  - 'CardList Objects': card-lists.md
  - 'CardSet Objects': card-sets.md
  - 'CardSetCollection Objects': card-set-collections.md
  - 'Deck Objects': decks.md
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: true
          paths: ['src']
repo_name: HarrisonTotty/fab
repo_url: https://github.com/HarrisonTotty/fab
site_name: Flesh and Blood TCG Analysis Library API Documentation
theme: material
